version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "main"
    reviewers:
      - "Sage-Bionetworks/rocc-maitainers"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "main"
    reviewers:
      - "Sage-Bionetworks/rocc-maitainers"