version: '3.8'

services:
  rocc-db:
    image: sagebionetworks/mongo:4.4.8
    container_name: rocc-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
      - MONGO_USERNAME
      - MONGO_PASSWORD
    networks:
      - rocc-networks

  rocc-service:
    image: sagebionetworks/rocc-service:0.7.0
    container_name: rocc-service
    restart: always
    environment:
      - SERVER_PROTOCOL
      - SERVER_DOMAIN
      - SERVER_PORT
      - DB_PROTOCOL
      - DB_DOMAIN=rocc-db
      - DB_PORT
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
    networks:
      - rocc-networks
    ports:
      - "8080:8080"
    depends_on:
      - rocc-db

  rocc-app:
    image: sagebionetworks/rocc-app:0.5.0
    container_name: rocc-app
    build: .
    restart: always
    environment:
      - ENVIRONMENT
      - API_URL
      - APP_VERSION
      - SEED_DATABASE
      - SERVICE_HOST=rocc-service
      - SERVICE_PORT=8080
    networks:
      - rocc-networks
    ports:
      - "80:80"
    depends_on:
      - rocc-service

networks:
  rocc-networks:
