version: '3.8'

services:
  rocc-database:
    image: sagebionetworks/mongo:${DATABASE_VERSION}
    container_name: rocc-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
      - MONGO_USERNAME
      - MONGO_PASSWORD
    networks:
      - rocc-networks

  rocc-service:
    image: sagebionetworks/rocc-service:${SERVICE_VERSION}
    container_name: rocc-service
    restart: always
    ports:
      - '8080:8080'
    environment:
      - SERVER_PROTOCOL
      - SERVER_DOMAIN
      - SERVER_PORT=8080
      - DB_PROTOCOL
      - DB_DOMAIN=rocc-database
      - DB_PORT
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
    networks:
      - rocc-networks
    depends_on:
      - rocc-database

  rocc-app:
    image: sagebionetworks/rocc-app:${APP_VERSION}
    container_name: rocc-app
    build: .
    restart: always
    environment:
      - ENVIRONMENT=prod
      - API_URL=http://localhost/api
      - APP_VERSION=x.y.z
      - SEED_DATABASE=true
    networks:
      - rocc-networks
    depends_on:
      - rocc-service

  nginx:
    image: nginx:1.19.6-alpine
    container_name: nginx
    restart: always
    environment:
      - SERVER_HOST=rocc-service
      - SERVER_PORT=8080
      - CLIENT_HOST=rocc-app
      - CLIENT_PORT=80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/templates:/etc/nginx/templates:ro
    networks:
      - rocc-networks
    ports:
      - '80:80'
    depends_on:
      - rocc-app

networks:
  rocc-networks:
