/**
 * Registry of Open Community Challenge API
 * The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
 *
 * The version of the OpenAPI document: 0.1.7
 * Contact: thomas.schaffter@sagebionetworks.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChallengeStatus } from './challengeStatus';


/**
 * An object that describes how to filter Challenges
 */
export interface ChallengeFilter { 
    /**
     * Keep the challenges whose name include this term
     */
    name?: string;
    status?: ChallengeStatus;
    /**
     * Keep the challenges organized by this person
     */
    organizer?: string;
    /**
     * Keep the challenges associated to this tag
     */
    tag?: string;
}

