/**
 * Registry of Open Community Challenge API
 * The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
 *
 * The version of the OpenAPI document: 0.1.7
 * Contact: thomas.schaffter@sagebionetworks.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The status of the challenge
 */
export type ChallengeStatus = 'upcoming' | 'open' | 'closed';

export const ChallengeStatus = {
    Upcoming: 'upcoming' as ChallengeStatus,
    Open: 'open' as ChallengeStatus,
    Closed: 'closed' as ChallengeStatus
};

