/**
 * Registry of Open Community Challenge API
 * The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
 *
 * The version of the OpenAPI document: 0.1.7
 * Contact: thomas.schaffter@sagebionetworks.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An object that describes how to filter Persons
 */
export interface PersonFilter { 
    /**
     * Keep the persons whose first name starts with this term
     */
    firstName?: string;
    /**
     * Keep the persons whose last name starts with this term
     */
    lastName?: string;
    /**
     * Keep the persons whose email matches this term
     */
    email?: string;
    /**
     * Keep the persons who belong to this organization
     */
    organization?: string;
}

