/**
 * Registry of Open Community Challenge API
 * The OpenAPI specification implemented by the Challenge Registries. # Introduction TBA 
 *
 * The version of the OpenAPI document: 0.1.7
 * Contact: thomas.schaffter@sagebionetworks.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserCreateResponse } from './userCreateResponse';
import { UserCreateRequest } from './userCreateRequest';


/**
 * A user of the portal
 */
export interface User { 
    /**
     * The username of the user
     */
    username?: string;
    /**
     * The role of the user
     */
    role?: User.RoleEnum;
    /**
     * The first name of the person
     */
    firstName: string;
    /**
     * The last name of the person
     */
    lastName: string;
    /**
     * An email address
     */
    email?: string;
    /**
     * The organizations the person belongs to
     */
    organizationIds: Array<string>;
}
export namespace User {
    export type RoleEnum = 'user' | 'admin';
    export const RoleEnum = {
        User: 'user' as RoleEnum,
        Admin: 'admin' as RoleEnum
    };
}


